### ISSUE TITLE
io object not found when running from remote host

### ISSUE THREAD

**Issue by ejeklint** [sbstjn/noduino#1]
I'm trying to access noduino server from another machine with only partial success. After I figured out that \* is the way to specify any ip (blush) and that "localhost:8090" was hard coded in the examples (replaced it with ":8090") I almost got it working. But I get an error:

Noduino.Socket.js line 53: Can't find variable: io

when trying to connect to the board. I'm still not clever enough about javascript and the architecture behind socket.io to figure out why it doesn't load when not running the client on localhost, so I can't provide a patch yet...

**Comment by sbstjn** [comment]
Please have a look at `views/layout.jade` line 9 for changing the file location of socket.io.js. Using a central definition for file locations and ports is definitely a point for an updated future version of noduino…

**Comment by ejeklint** [comment]
OK, but shouldn't it just work with referring to `/socket.io/socket.io.js` instead of `http://localhost:8090/socket.io/socket.io.js`? I fail to understand why it wouldn't.

**Comment by musterknabe** [comment]
socket.io is listening on a different port (8080 vs 8090). But I guess you figured that one out in the last two years or moved on ;)
I fixed that in PR #26 if you still need it, tho.
