### ISSUE TITLE
git clone is defaulting to gh-pages branch

### ISSUE THREAD

**Issue by cole-gillespie** [sbstjn/noduino#2]
the instructions you have for some reason are defaulting a clone to the gh-pages branch so submodule init does not work either

**Comment by sbstjn** [comment]
Somehow GitHub had the `gh-pages` branch as default, but the settings page showed the master branch. Fixed it with setting default branch to `gh-pages` and back to `master` again. Thanks!

**Comment by cole-gillespie** [comment]
no problem
